@extends('layouts.app')


@section('page-content')

    <style>
        body {
            background: #f5f5f5;
        }

        .annexure-page {
            background: #ffffff;
            min-height: 1120px;
            padding: 50px 60px 140px 60px;
            position: relative;
            font-family: Arial, Helvetica, sans-serif;
        }

        /* HEADER */
        .annexure-header img.logo {
            height: 55px;
        }

        .annexure-header img.pattern {
            position: absolute;
            top: 0;
            right: 0;
            width: 300px;
        }

        /* TITLE */
        .annexure-title {
            margin-top: 40px;
            margin-bottom: 25px;
        }

        .annexure-title h4 {
            font-weight: bold;
            margin-bottom: 5px;
        }

        /* EMPLOYEE INFO */
        .emp-info p {
            margin-bottom: 4px;
            font-weight: 600;
        }

        /* TABLE */
        .salary-table {
            width: 100%;
            border-collapse: collapse;
            background: #ffffff;
            color: #000000;
            margin-top: 25px;
            font-size: 14px;
        }

        .salary-table th,
        .salary-table td {
            border: 1px solid #000000;
            padding: 8px 10px;
        }

        .salary-table th,
        .salary-table td {
            border: 1px solid #000;
            padding: 8px 10px;
        }

        .salary-table .fw-bold {
            font-weight: bold;
        }


        /* FOOTER */
        .annexure-footer {
            position: absolute;
            bottom: 25px;
            left: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: #000;
        }

        .annexure-footer span {
            display: block;
            margin-top: 4px;
        }
    </style>

    <div class="content container-fluid">

        <!-- Page Header -->
        <x-breadcrumb class="col">
            <x-slot name="title">{{ __('Payslip') }}</x-slot>
            <ul class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ __('Preview Payslip') }}
                </li>
            </ul>
            <x-slot name="right">
                <div class="col-auto float-end ms-auto">
                    <div class="btn-group btn-group-sm" x-data="{
                        printContent: function(){
                            const originalContents = $('body').html();
                            var printContents = $('#payslipSection').html()
                            $('body').empty().html(printContents);
                            window.print();
                            $('body').html(originalContents);
                    }}">
                        <button class="btn btn-white" onclick='window.location.href="{{ route('payslips.index') }}"'>{{ __('Go Back') }}</button>
                        <button class="btn btn-white" @click="function(){
                            let pWidth = 595.28; // the width of a4
                            let srcWidth = document.querySelector('body > div').scrollWidth;
                            let margin = 18; // narrow margin - 1.27 cm (36);
                            let scale = (pWidth - margin * 2) / srcWidth;
                            const doc = new  jsPDF('p', 'pt', 'a4', true);
                            doc.html(document.getElementById('payslipSection'),{
                                callback: function (doc) {
                                    let totalPages = doc.internal.getNumberOfPages()
                                    {{-- //temporal solution for the blanks pages generated by jspdf --}}
                                    for (var i = 2; i <= totalPages; i++) {
                                        doc.setPage(i);
                                        doc.deletePage(i);
                                        i--;
                                        totalPages--;
                                    }
                                    doc.save('{{ $payslip->ps_id }}.pdf');
                                },
                                html2canvas: {
                                    useCORS: true,
                                    allowTaint: true,
                                    letterRendering: true,
                                    scale: scale,
                                },
                                x: margin,
                                y: margin,
                                autoPaging: 'text',
                                jsPDF: doc,
                            })
                        }">{{ __('PDF') }}</button>
                        <button class="btn btn-white" @click="printContent"><i class="fa-solid fa-print fa-lg"></i> {{ __('Print') }}</button>
                    </div>
                </div>
            </x-slot>
        </x-breadcrumb>
        <!-- /Page Header -->

     

        <div class="annexure-page" id="payslipSection">

            {{-- HEADER --}}
            <div class="annexure-header">
                <img src="{{ asset('images/bingo.png') }}" class="logo" alt="Logo">
                <img src="{{ asset('images/latterhead.png') }}" class="pattern" alt="">
            </div>

            {{-- TITLE --}}
            <div class="annexure-title">
                <strong>Payslip of the month of {{ $payslip->payslip_date ?? format_date($payslip->created_at) }}</strong>
            </div>

            {{-- EMPLOYEE INFO --}}
            <div class="emp-info">
                <p>Employee Name: {{ $payslip->employee->user->fullname }}</p>
                <p>Designation: {{ $employee->designation->name ?? 'XX' }}</p>
                <p>Location: {{ $employee->location ?? 'Noida' }}</p>
                <p>Date of Joining: {{ format_date($employee->date_joined) }}</p>
                <p>Salary Month: {{ $payslip->payslip_date ?? format_date($payslip->created_at) }}</p>
            </div>

            {{-- SALARY TABLE --}}
            <table class="salary-table">
                <thead>
                    <tr>
                        <th width="40%">SECTION</th>
                        <th width="30%">AMOUNT</th>
                        <th width="30%">DETAILS</th>
                    </tr>
                </thead>
                <tbody>

                    @php
                        // Calculate totals
                        $baseSalary = $employee->salaryDetails->base_salary ?? 0;
                        $totalAllowances = $allowances->sum('amount') ?? 0;
                        $totalDeductions = $deductions->sum('amount') ?? 0;
                        $grossSalary = $baseSalary + $totalAllowances;
                        $hraAllowance = $allowances->where('name', 'HRA')->first()->amount ?? 0;
                        $otherAllowances = $totalAllowances - $hraAllowance;
                        
                        // Employer contributions (you may need to adjust these based on your data structure)
                        $employerPF = 0;
                        $employerESI = 0;
                        foreach($deductions as $deduction) {
                            if(stripos($deduction->name, 'employer') !== false || stripos($deduction->name, 'pf') !== false) {
                                $employerPF += $deduction->amount ?? 0;
                            }
                            if(stripos($deduction->name, 'employer') !== false || stripos($deduction->name, 'esi') !== false) {
                                $employerESI += $deduction->amount ?? 0;
                            }
                        }
                        
                        $totalEmployerContribution = $employerPF + $employerESI;
                        $ctc = $grossSalary + $totalEmployerContribution;
                    @endphp   

                    {{-- Monthly Salary Structure (Earnings) --}}
                    
                    <tr>
                        <td>Basic Salary</td>
                        <td>{{ $currency }} {{ number_format($baseSalary, 2) }}</td>
                        <td>50% of Gross</td>
                    </tr>
                    @if($hraAllowance > 0)
                    <tr>
                        <td>HRA</td>
                        <td>{{ $currency }} {{ number_format($hraAllowance, 2) }}</td>
                        <td>40% of Basic</td>
                    </tr>
                    @endif
                    @if($otherAllowances > 0)
                    <tr>
                        <td>Other Allowances</td>
                        <td>{{ $currency }} {{ number_format($otherAllowances, 2) }}</td>
                        <td>Remaining part of Gross</td>
                    </tr>
                    @endif
                    <tr class="fw-bold total-row">
                        <td>Total Gross Salary</td>
                        <td>{{ $currency }} {{ number_format($grossSalary, 2) }}</td>
                        <td></td>
                    </tr>

                    {{-- Statutory Deductions --}}
                    <tr class="section-row">
                        <td colspan="3">Statutory Deductions</td>
                    </tr>
                    @php $hasDeductions = false; @endphp
                    @foreach($deductions as $deduction)
                        @if(stripos($deduction->name, 'employee') !== false || stripos($deduction->name, 'pf') !== false || stripos($deduction->name, 'esi') !== false)
                            @php $hasDeductions = true; @endphp
                            <tr>
                                <td>{{ $deduction->name }}</td>
                                <td>{{ $currency }} {{ number_format($deduction->amount, 2) }}</td>
                                <td></td>
                            </tr>
                        @endif
                    @endforeach
                    @if(!$hasDeductions)
                    <tr>
                        <td>Employee PF</td>
                        <td>{{ $currency }} 0.00</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Employee ESI</td>
                        <td>{{ $currency }} 0.00</td>
                        <td></td>
                    </tr>
                    @endif
                    <tr class="fw-bold total-row">
                        <td>Total Deductions</td>
                        <td>{{ $currency }} {{ number_format($totalDeductions, 2) }}</td>
                        <td></td>
                    </tr>

                    {{-- Net Salary (In-Hand) --}}
                    <tr class="section-row">
                        <td colspan="3">Net Salary (In-Hand)</td>
                    </tr>
                    <tr class="fw-bold net-pay-row">
                        <td>Net Pay</td>
                        <td>{{ $currency }} {{ number_format($payslip->net_pay, 2) }}</td>
                        <td></td>
                    </tr>

                    {{-- Employer Contributions (CTC) --}}
                    <tr class="section-row">
                        <td colspan="3">Employer Contributions (CTC)</td>
                    </tr>
                    @if($employerPF > 0)
                    <tr>
                        <td>Employer PF</td>
                        <td>{{ $currency }} {{ number_format($employerPF, 2) }}</td>
                        <td></td>
                    </tr>
                    @else
                    <tr>
                        <td>Employer PF</td>
                        <td>{{ $currency }} 0.00</td>
                        <td></td>
                    </tr>
                    @endif
                    @if($employerESI > 0)
                    <tr>
                        <td>Employer ESI</td>
                        <td>{{ $currency }} {{ number_format($employerESI, 2) }}</td>
                        <td></td>
                    </tr>
                    @else
                    <tr>
                        <td>Employer ESI</td>
                        <td>{{ $currency }} 0.00</td>
                        <td></td>
                    </tr>
                    @endif
                    <tr class="fw-bold total-row">
                        <td>Total Employer Contribution</td>
                        <td>{{ $currency }} {{ number_format($totalEmployerContribution, 2) }}</td>
                        <td></td>
                    </tr>

                    {{-- CTC Per Annum --}}
                    <tr class="fw-bold ctc-row">
                        <td>CTC Per Annum</td>
                        <td>{{ $currency }} {{ number_format($ctc * 12, 2) }}</td>
                        <td></td>
                    </tr>

                </tbody>
            </table>


        </div>

    </div>
@endsection


@push('page-scripts')
@endpush